<a href="https://colab.research.google.com/github/Wishy-S/LearningML/blob/master/LearningNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a = [1,2,3,4,5]
arr = np.array(a)

In [7]:
arr.shape

(5,)

In [11]:
type(arr),type(a)

(numpy.ndarray, list)

In [14]:
a1 = [1,2,3,4,5]
a2 = [2,3,4,5,6]
a3 = [9,7,6,8,9]
arrr = np.array([a1,a2,a3])

In [17]:
arr = arrr
arr.shape

(3, 5)

In [20]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [23]:
rearr = arr.reshape(5,3)
rearr

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [27]:
arr = np.arange(0,100)
rearr = arr.reshape(10,10)
rearr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
rearr[3:6,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])