<a href="https://colab.research.google.com/github/Wishy-S/LearningML/blob/master/LearningNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = [1,2,3,4,5]
arr = np.array(a)

In [7]:
arr.shape

(5,)

In [11]:
type(arr),type(a)

(numpy.ndarray, list)

In [14]:
a1 = [1,2,3,4,5]
a2 = [2,3,4,5,6]
a3 = [9,7,6,8,9]
arrr = np.array([a1,a2,a3])

In [17]:
arr = arrr
arr.shape

(3, 5)

In [20]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [23]:
rearr = arr.reshape(5,3)
rearr

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [27]:
arr = np.arange(0,100)
rearr = arr.reshape(10,10)
rearr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
#understanding step parameter of arange
arr = np.arange(10,101,step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [29]:
rearr[3:6,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [67]:
#default num value is 50
#takes  7 parameters as input 
#axis may be something related to dimension of the array
np.linspace(0,10,num=100,endpoint=False,axis = 0).reshape(4,25)


array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
        1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4],
       [2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
        3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
        6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4],
       [7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
        8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#copy 
#what this do is it basically replaces all the values from the given index till last with the provided value
arr[2:] =100
arr

array([  1,   2, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr1 = arr #here reference arr got assigned to arr1 and not a copy
arr1[2:] = 500
arr1,arr
#as we can see here because of reference type assignment the previous array value also got changed but lets say we want to prevent it then for that
#we have copy()

(array([  1,   2, 500, 500, 500, 500, 500, 500, 500, 500]),
 array([  1,   2, 500, 500, 500, 500, 500, 500, 500, 500]))

In [11]:
#copy()
arr1 = arr.copy() #instead of directly assigning 
arr1[2:] = 1000
arr1,arr
#now here we assigned the copy to the arr1 so the previous array values remained as it is

(array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]),
 array([  1,   2, 500, 500, 500, 500, 500, 500, 500, 500]))

In [19]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
np.random.rand(3,3)

array([[0.69142287, 0.36364357, 0.36423402],
       [0.9731049 , 0.99800353, 0.2582793 ],
       [0.33640083, 0.91610618, 0.39623019]])

In [21]:
np.random.randn(3,3)

array([[ 0.07422061,  0.78784287,  0.6334325 ],
       [ 1.31490495, -0.98815777,  0.75041514],
       [-0.10170204,  1.39244735, -0.01259737]])

In [28]:
np.random.randint(0,100,8)

array([44, 35, 82, 84, 48, 13, 88, 65])

In [31]:
np.random.random_sample((3))

array([0.92638251, 0.86238795, 0.22353852])